# Generated by Django 4.2.9 on 2024-01-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mista', '0002_place_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='User',
            new_name='user',
        ),
    ]
