# Generated by Django 4.2.9 on 2024-02-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mista', '0004_city_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'postalcode')},
        ),
    ]
