# Generated by Django 4.2.9 on 2024-04-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mista', '0005_alter_city_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='registration_number',
        ),
    ]
